#:schema node_modules/wrangler/config-schema.json
name = "webhook-ingress"
main = "source/index.ts"
compatibility_date = "2025-08-30"
compatibility_flags = ["nodejs_als"]
workers_dev = false
routes = [{ pattern = "webhook-ingress.thatskyapplication.com", custom_domain = true }]

[observability]
enabled = true
