#:schema node_modules/wrangler/config-schema.json
name = "webhook-ingress"
main = "source/index.ts"
compatibility_date = "2024-12-18"
workers_dev = false
routes = [{ pattern = "webhook-ingress.thatskyapplication.com", custom_domain = true }]

[observability]
enabled = true
